version: "2.1"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /media/alnav/Plex/shows/shows:/tv
      - /media/alnav/HDD1/transmission/downloads:/downloads
    ports:
      - 8989:8989
    restart: always