version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /media/alnav/Plex/movies:/movies
      - /media/alnav/HDD1/transmission/downloads:/downloads
    ports:
      - 7878:7878
    restart: always