version: '3.3'
services:
  adguardhome:
    container_name: adguardhome
    restart: always
    volumes:
      - ./adguard_data:/opt/adguardhome/work
      - ./adguard_config:/opt/adguardhome/conf
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    image: adguard/adguardhome
    networks:
      - web_network
networks:
  web_network:
    external: true

volumes:
  adguard_data:
  adguard_config: