version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    networks:
      - web_network
    ports:
      - "8096:8096"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /media/alnav/Plex/shows/shows:/shows
      - /media/alnav/Plex/movies:/movies:ro
    restart: 'always'
    environment:
      - .env

networks:
  web_network:
    external: true