version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000 - PGID=1000 - TZ=Etc/UTC
      - USER=$USER #optional
      - PASS=$PASS #optional
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./watch:/watch
    ports:
       - 51413:51413
       - 51413:51413/udp
    networks:
      - web_network
    restart: always
networks:
  web_network:
    external: true